version: '3.9'

services:
  backend:
    container_name: backend
    image: com.gafarov/backend:latest
    build: .
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DB_SERVER=${DB_SERVER}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - STATISTIC_URL=${STATISTIC_URL}
      - STATISTIC_AUTH_USERNAME=${STATISTIC_AUTH_USERNAME}
      - STATISTIC_AUTH_PASSWORD=${STATISTIC_AUTH_PASSWORD}
      - STATISTIC_REQUEST_LOGIN=${STATISTIC_REQUEST_LOGIN}
      - STATISTIC_REQUEST_PASSWORD=${STATISTIC_REQUEST_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - /home/iskander/test:/app/files
    restart: unless-stopped
