version: '3.9'

services:
  backend:
    image: com.gafarov/backend:latest
    ports:
      - "8080:8080"
    networks:
      monitoring:
    environment:
      - SPRING_DATASOURCE_URL=${PSQL_JDBC_URL}
      - SPRING_DATASOURCE_USERNAME=${PSQL_JDBC_USER}
      - SPRING_DATASOURCE_PASSWORD=${PSQL_JDBC_PASS}

    
    