spring:
  liquibase:
    enabled: true
    change-log: /db/changelog/master.xml
  datasource:
    url: jdbc:postgresql://${DB_SERVER:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:postgres}
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
  jpa:
    show-sql: true
    database: postgresql
  servlet:
    multipart:
      max-file-size: 10MB
application:
  security:
    jwt:
      secret-key: ${JWT_SECRET:WS8ShcPWpwyhJcF4QggP2GMsG09mocYzEelRXWeH1K0=}
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: swagger
server:
  servlet:
    context-path: /api/v1
amazon:
  access-key: ${ACCESS_KEY}
  secret-key: ${SECRET_KEY}
  bucket-name: ${BUCKET_NAME:48743bfe-bastion}
  endpoint-url: s3.timeweb.com
  region: ru-1