spring:
  liquibase:
    enabled: true
    change-log: /db/changelog/master.xml
  datasource:
    url: jdbc:postgresql://${DB_SERVER}:${POSTGRES_PORT}/${POSTGRES_DB}
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    database: postgresql
  servlet:
    multipart:
      max-file-size: 10MB
application:
  security:
    jwt:
      secret-key: ${JWT_SECRET}
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: swagger
server:
  servlet:
    context-path: /api/v1
statistic-service:
  url: ${STATISTIC_URL}
  auth:
    username: ${STATISTIC_AUTH_USERNAME}
    password: ${STATISTIC_AUTH_PASSWORD}
  request:
    login: ${STATISTIC_REQUEST_LOGIN}
    password: ${STATISTIC_REQUEST_PASSWORD}
file:
  storage:
    root-directory: /app/files
