spring:
  liquibase:
    enabled: true
    change-log: /db/changelog/master.xml
  datasource:
    url: jdbc:postgresql://${DB_SERVER}:${POSTGRES_PORT}/${POSTGRES_DB}
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    database: postgresql
  servlet:
    multipart:
      max-file-size: 10MB
application:
  security:
    jwt:
      secret-key: ${JWT_SECRET}
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: swagger
server:
  servlet:
    context-path: /api/v1
amazon:
  access-key: ${ACCESS_KEY}
  secret-key: ${SECRET_KEY}
  bucket-name: ${BUCKET_NAME}
  endpoint-url: ${ENDPOINT_URL}
  region: ${REGION}