#on:
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]
#
#permissions:
#  contents: read
#
#jobs:
#  build:
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v3
#    - name: Set up JDK 17
#      uses: actions/setup-java@v3
#      with:
#        java-version: '17'
#        distribution: 'temurin'
#    - name: build and tests
#      uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
#      with:
#        arguments: build
#  deploy:
#    needs: build
#    runs-on: ubuntu-latest
#    if: github.ref == 'refs/heads/main'
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v3
#      - name: Run command on remote server
#        uses: D3rHase/ssh-command-action@v0.2.2
#        with:
#          host: ${{secrets.SSH_HOST}}
#          user: ${{secrets.SSH_USER}}
#          private_key: ${{secrets.SSH_PRIVATE_KEY}}
#          command: |
#            cd ${{ secrets.PROJECT_FOLDER }};
#            git checkout main;
#            git pull;
#            docker-compose down;
#            ./gradlew dockerBuildImage;
#            docker-compose up -d;
#
#
